version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: django-sample-container
    volumes:
      - ./:/usr/src
    ports:
      - "8000:8000"
    tty: true
